# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {Common 17-41} -limit 10000000
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a35tcpg236-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir /media/ad/Area51/workspace/col215_prac_lab/vivado/lab6/lab6.cache/wt [current_project]
set_property parent.project_path /media/ad/Area51/workspace/col215_prac_lab/vivado/lab6/lab6.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo /media/ad/Area51/workspace/col215_prac_lab/vivado/lab6/lab6.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_vhdl -library xil_defaultlib /media/ad/Area51/workspace/col215_prac_lab/lab6/submission/lab6_multiplier.vhd
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc /media/ad/Area51/workspace/col215_prac_lab/lab6/lab6_multiplier.xdc
set_property used_in_implementation false [get_files /media/ad/Area51/workspace/col215_prac_lab/lab6/lab6_multiplier.xdc]


synth_design -top cla_adder_8 -part xc7a35tcpg236-1


write_checkpoint -force -noxdef cla_adder_8.dcp

catch { report_utilization -file cla_adder_8_utilization_synth.rpt -pb cla_adder_8_utilization_synth.pb }
