# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a35tcpg236-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir /media/ad/TheLibrary/col215_lab/vivado/practice/practice.cache/wt [current_project]
set_property parent.project_path /media/ad/TheLibrary/col215_lab/vivado/practice/practice.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo /media/ad/TheLibrary/col215_lab/vivado/practice/practice.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_vhdl -library xil_defaultlib /media/ad/Area51/workspace/col215_prac/practice.vhd
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}

synth_design -top lab6_multiplier -part xc7a35tcpg236-1


write_checkpoint -force -noxdef lab6_multiplier.dcp

catch { report_utilization -file lab6_multiplier_utilization_synth.rpt -pb lab6_multiplier_utilization_synth.pb }
